CPPFLAGS += \
	-DIMG_ADDRESS=$(IMG_ADDRESS)		\
	-DIMG_SIZE=$(IMG_SIZE)			\
	-DJUMP_ADDR=$(JUMP_ADDR)		\
	-DTOP_OF_MEMORY=$(TOP_OF_MEMORY)	\
	-DMACH_TYPE=$(MACH_TYPE)		\

ASFLAGS += -DJUMP_ADDR=$(JUMP_ADDR)		\
	-DTOP_OF_MEMORY=$(TOP_OF_MEMORY)	\
	-DMACH_TYPE=$(MACH_TYPE)		\

ifeq ($(CONFIG_APP_CHECK),y)
CPPFLAGS += -DCONFIG_APP_CHECK
endif

ifeq ($(CONFIG_LONG_TEST),y)
CPPFLAGS += -DCONFIG_LONG_TEST
endif

ifeq ($(CONFIG_DEBUG),y)
CPPFLAGS += -DCONFIG_DEBUG
endif

ifeq ($(CONFIG_VERBOSE),y)
CPPFLAGS += -DCONFIG_VERBOSE
endif

ifeq ($(CONFIG_HW_INIT),y)
CPPFLAGS += -DCONFIG_HW_INIT
endif

ifeq ($(CONFIG_USER_HW_INIT),y)
CPPFLAGS += -DCONFIG_USER_HW_INIT
endif

